### ISSUE TITLE
dlopen crashes using RTLD_NOW

### ISSUE THREAD

**Issue by xantares** [dlfcn-win32/dlfcn-win32#32]
since aa1401b (#20) using RTLD_NOW (replace RTLD_GLOBAL in test.c) with mingw crashes:
```library = dlopen( "testdll.dll", RTLD_NOW );```

I discovered this while updating from 1.0.0 to 1.1.0, both i686 & x86_84, from linux/mingw/gcc6.3.1

**Comment by traversaro** [comment]
Thanks for the bug report @xantares . I definitely not an expert on `RTLD_NOW`, but I will investigate the problem. Any additional hint or possible solution is extremely welcome, thanks!

**Comment by traversaro** [comment]
As highlighted by https://ci.appveyor.com/project/dlfcn-win32/dlfcn-win32/build/1.0.1/job/qqr8sxnrakseufbx , `RTLD_NOW` crashes the library also using MSVC . This should simplify solving the issue.

**Comment by traversaro** [comment]
Hi @xantares ,  
   the PR that you proposed to highlight the issue ( https://github.com/dlfcn-win32/dlfcn-win32/pull/37 ) stop crashing if bug https://github.com/dlfcn-win32/dlfcn-win32/issues/34 is fixed . Note that the test continues to fail, but I think that is due to the fact that the specs: 
> If neither RTLD_GLOBAL nor RTLD_LOCAL are specified, then the default behavior is unspecified.
Passing only `RTLD_NOW` means that neither `RTLD_GLOBAL` nor `RTLD_LOCAL` flags are specified, and apparently for `dlfcn-win32` the default behavior is `RTLD_LOCAL` . Do you think there is any reason to change that?

**Comment by xantares** [comment]
I really cannot help here, but the crash is gone and the test is ok since your fix, thanks!

**Comment by traversaro** [comment]
Ok, thanks a lot @xantares !
