### ISSUE TITLE
dlsym multiple defintion

### ISSUE THREAD

**Issue by ambitslix** [dlfcn-win32/dlfcn-win32#71]
Hello,

I'm using the following for a tracer in std::exceptions:
```
extern "C"
{
  void __cxa_throw(void* ex, void* info, void (*dest)(void*))
  {
    trace code here...
    static void (*const rethrow)(void*, void*, void (*)(void*)) __attribute__((noreturn)) = (void (*)(void*, void*, void (*)(void*)))dlsym(RTLD_NEXT, "__cxa_throw");

    rethrow(ex, info, dest);
  }
}
```
It works well under Linux with dl however when I cross compile with dflcn-win32 I get :

```
libstdc++.a(eh_throw.o):(.text$__cxa_throw+0x0): multiple definition of `__cxa_throw'
```
I'm using the MingW static cross compiler, perhaps I should do dynamic linking or, perhaps link order or perhaps I need a linker flag?

Thank you

**Comment by pali** [comment]
Probably you need to mark your `__cxa_throw` implementation with `__declspec(dllexport)`.

Then main problem is that symbols on PE targets are resolved at compile/link time. So once you link symbol `A` in your executable `B` with library `C` then always this combination would be used.

`RTLD_NEXT` is locating symbol in executable at runtime. So to make it working, you need to have loaded one symbol name more times.

As `__cxa_throw` is in `libstdc++.a` you have to avoid using libstdc++ at compile/link time if you want to use your `__cxa_throw` implementation. But I guess you cannot avoid it as you want to use C++.

Anyway, I'm not sure if you can use `dlsym/RTLD_NEXT` for static linked libraries. I think it needs working with dynamic DLL libraries. And this probably applies also for ELF targets. On Linux it is working because you are for sure linking std library dynamically.

**Comment by pali** [comment]
`dlsym`/`dlfcn` is for dynamic linked code/libraries. Nott for static linked `.a` libraries. So in above setup with static linked `libstdc++.a` library, `dlsym` would not work.
